### PR TITLE
convert Pluto to Jupyter notebook

### PR DESCRIPTION
**Pull request by vdayanand**
- new method `convert2jupyter` converts pluto notebooks to jupyter
- rename method `convert_notebook` to `convert2pluto`

### CODE REVIEW

**Comment by fonsp** [comment]
How about `pluto2jupyter` instead of `convert2jupyter`?

**Comment by vdayanand** [comment]
That does sound better. Maybe change the package name itself? I couldn't come up with one.

**Comment by fonsp** [comment]
Eventually it will go into PlutoUtils.jl

**Comment by fonsp** [comment]
(so don't register this package 😊)

**Comment by fonsp** [comment]
Well only if you agree of course! Feel free to do what you want!

**Comment by fonsp** [comment]
You can already write your PR to https://github.com/fonsp/PlutoUtils.jl, but it would be nice if we also have some basic test notebooks

**Comment by vdayanand** [comment]
Sure. I will write some tests and put up a PR soon.

**Comment by fonsp** [comment]
awesome

**Pull request merged**
